obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.508, -0.305], [0.3302, -0.305], [0.3302, 0.305], [-0.508, 0.305]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

#observation_sources: laser_scan_sensor point_cloud_sensor
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: /laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud2, topic: /camera/depth_registered/points , marking: true, clearing: true}

static_map: false
